const data = [
    "I like to learn more about myself",
    "I can play a musical instrument",
    "I find it easiest to solve problems when I am doing something physical",
    "I often have a song or piece of music in my mind",
    "I find budgeting and managing my money easy",
    "I find it easy to make up stories",
    "I have always been very coordinated",
    "When talking to someone, I tend to listen to the words they use not just what they mean",
    "I enjoy cross words, word searches or other word puzzles",
    "I don’t like ambiguity, I like things to be clear",
    "I enjoy logic puzzles such as 'sudoku'",
    "I like to meditate",
    "Music is very important to me",
    "I am a convincing liar",
    "I play a sport or dance",
    "I am very interested in psychometrics (personality testing) and IQ tests",
    "People behaving irrationally annoy me",
    "I find that the music that appeals to me is often based on how I feel emotionally",
    "I am a very social person and like being with other people",
    "I like visiting zoo with friends and relatives",
    "I normally don't take out printed statement from ATM for balance confirmation. I do it only when it's very very important",
    "I like to be systematic and thorough",
    "I find graphs and charts easy to understand",
    "I can throw things well - darts, skimming pebbles, frisbees, etc",
    "I find it easy to remember quotes or phrases",
    "I can always recognize places that I have been before, even when I was very young",
    "I represented my school/ college in various places as a team member of scouts and guides",
    "I enjoy a wide variety of musical styles",
    "When I am concentrating I tend to doodle",
    "I can manipulate people if I choose to",
    "I can predict my feelings and behaviors in certain situations fairly accurately",
    "I have an aquarium in my home and I enjoy feeding fishes there",
    "I find mental arithmetic easy",
    "I can identify most sounds without seeing what causes them",
    "At school one of my favorite subjects is / was English",
    "I like to think through a problem carefully, considering all the consequences",
    "I enjoy debates and discussions",
    "I love adrenaline sports and scary rides",
    "I enjoy individual sports best",
    "I care about how those around me feel",
    "My house is full of pictures and photographs",
    "I love watching Tv channels like National Geography/ Animal Planet/ Discovery",
    "I enjoy and am good at making things - I'm good with my hands",
    "I enjoy caring for pets and other animals",
    "I like having music on in the background",
    "I am associated with a group/ NGO working for conservation of nature and environment",
    "I find it easy to remember telephone numbers",
    "I set myself goals and plans for the future",
    "I am a very tactile (demonstrative) person, love doing on my own",
    "I can tell easily whether someone likes me or dislikes me",
    "I can easily imagine how an object would look from another perspective",
    "I never use instructions for flat-pack furniture",
    "I find it easy to talk to new people",
    "I often visit park, botanical garden etc",
    "To learn something new, I need to just get on and try it",
    "I often see clear images when I close my eyes",
    "I don’t use my fingers when I count",
    "I often talk to myself – out loud or in my head",
    "At school I loved / love music lessons",
    "When I am abroad, I find it easy to pick up the basics of another language",
    "I find ball games easy and enjoyable",
    "My favourite subject at school is / was maths",
    "I always know how I am feeling",
    "I am realistic about my strengths and weaknesses",
    "I keep a diary",
    "I am very aware of other people’s body language",
    "My favorite subject at school was / is art",
    "I find pleasure in reading",
    "I can read a map easily",
    "It upsets me to see someone cry and not be able to help",
    "I am good at solving disputes between others",
    "I have always dreamed of being a musician or singer",
    "I prefer team sports",
    "Singing makes me feel happy",
    "I never get lost when I am on my own in a new place",
    "If I am learning how to do something, I like to see drawings and diagrams of how it works",
    "I am happy spending time alone",
    "My friends always come to me for emotional support and advice",
    "I enjoy studying about the earth and nature",
    "I enjoy being outside in all types of weather"
]
module.exports = data;